project:
  type: website
  output-dir: docs

website:
  title: "Bailie Wynbelt"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - projects.qmd # my new navbar page

format:
  html:
    theme: journal
    css: styles.css

editor: visual