project:
  type: website
  output-dir: docs

website:
  title: "Bailie Wynbelt"
  navbar:
   background: primary
   left:
     - href: index.qmd
       text: Home
     - about.qmd
     - resume.qmd
     - posts.qmd 

format:
  html:
    theme: lux
    css: styles.css
    code-link: true
    code-fold: show
    code-tools: true
    code-block-border-left: "green"

editor: visual